# Generated by Django 4.2.4 on 2023-12-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_requestservice_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='requestservice',
            options={'managed': False},
        ),
    ]
